# App name
spring.application.name=unidesk

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/unidesk
spring.datasource.username=root
spring.datasource.password=

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server port
server.port=8081
